name: 'Base Promote'
description: 'Promote deployment from one environment to another on Norce Base Platform'
author: 'NorceTech'

branding:
  icon: 'arrow-up-circle'
  color: 'green'

inputs:
  app:
    description: 'App name (defaults to repository name)'
    required: false
  from_environment:
    description: 'Source environment to promote from'
    required: true
  to_environment:
    description: 'Target environment to promote to'
    required: true
  api_url:
    description: 'Base Platform API URL'
    required: false
    default: 'https://base-api.norce.tech'
  api_key:
    description: 'Base Platform API key (identifies partner)'
    required: true

outputs:
  success:
    description: 'Whether the promotion was successful'
    value: ${{ steps.promote.outputs.success }}
  namespace:
    description: 'Kubernetes namespace'
    value: ${{ steps.promote.outputs.namespace }}
  git_commit_sha:
    description: 'Git commit SHA in GitOps repo'
    value: ${{ steps.promote.outputs.git_commit_sha }}
  previous_image_tag:
    description: 'Previous image tag in target environment'
    value: ${{ steps.promote.outputs.previous_image_tag }}
  new_image_tag:
    description: 'New image tag (from source environment)'
    value: ${{ steps.promote.outputs.new_image_tag }}
  message:
    description: 'Promotion message'
    value: ${{ steps.promote.outputs.message }}

runs:
  using: 'composite'
  steps:
    - name: Promote Deployment
      id: promote
      shell: bash
      env:
        API_URL: ${{ inputs.api_url }}
        API_KEY: ${{ inputs.api_key }}
        APP: ${{ inputs.app || github.event.repository.name }}
        FROM_ENV: ${{ inputs.from_environment }}
        TO_ENV: ${{ inputs.to_environment }}
      run: bash ${{ github.action_path }}/promote.sh
