name: 'Base Preview'
description: 'Manage PR preview environments on Norce Base Platform'
author: 'NorceTech'

branding:
  icon: 'eye'
  color: 'purple'

inputs:
  partner:
    description: 'Partner name on Base platform'
    required: true
  action:
    description: 'Action to perform (create, update, delete)'
    required: true
  image_tag:
    description: 'Image tag for the preview (not needed for delete)'
    required: false
  customer:
    description: 'Customer name (defaults to repository name)'
    required: false
  config_file:
    description: 'Path to config file'
    required: false
    default: '.base/config.yaml'
  api_url:
    description: 'Base Platform API URL'
    required: false
    default: 'https://api.base.norce.tech'
  token:
    description: 'Base Platform authentication token'
    required: true

outputs:
  success:
    description: 'Whether the action was successful'
    value: ${{ steps.preview.outputs.success }}
  preview_url:
    description: 'URL of the preview environment'
    value: ${{ steps.preview.outputs.preview_url }}
  namespace:
    description: 'Kubernetes namespace'
    value: ${{ steps.preview.outputs.namespace }}
  git_commit_sha:
    description: 'Git commit SHA in GitOps repo'
    value: ${{ steps.preview.outputs.git_commit_sha }}
  message:
    description: 'Result message'
    value: ${{ steps.preview.outputs.message }}

runs:
  using: 'composite'
  steps:
    - name: Read configuration
      id: config
      if: inputs.action != 'delete'
      shell: bash
      env:
        CONFIG_FILE: ${{ inputs.config_file }}
      run: |
        if [ -f "$CONFIG_FILE" ]; then
          echo "Found config file: $CONFIG_FILE"
          if command -v yq &> /dev/null; then
            ENV_CONFIG=$(yq -o=json ".environments.preview // {}" "$CONFIG_FILE")
          else
            ENV_CONFIG=$(python3 -c "
        import yaml, json, sys
        with open('$CONFIG_FILE') as f:
            data = yaml.safe_load(f)
            env_config = data.get('environments', {}).get('preview', {})
            print(json.dumps(env_config))
        " 2>/dev/null || echo "{}")
          fi
          echo "config=$ENV_CONFIG" >> $GITHUB_OUTPUT
        else
          echo "No config file found, using defaults"
          echo "config={}" >> $GITHUB_OUTPUT
        fi

    - name: Manage Preview Environment
      id: preview
      shell: bash
      env:
        API_URL: ${{ inputs.api_url }}
        TOKEN: ${{ inputs.token }}
        PARTNER: ${{ inputs.partner }}
        CUSTOMER: ${{ inputs.customer || github.event.repository.name }}
        ACTION: ${{ inputs.action }}
        IMAGE_TAG: ${{ inputs.image_tag }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        PR_BRANCH: ${{ github.head_ref }}
        COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_URL: ${{ github.event.pull_request.html_url }}
        CONFIG: ${{ steps.config.outputs.config }}
      run: |
        RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "${API_URL}/webhooks/preview" \
          -H "Authorization: Bearer ${TOKEN}" \
          -H "Content-Type: application/json" \
          -d "$(jq -n \
            --arg action "$ACTION" \
            --arg partner "$PARTNER" \
            --arg customer "$CUSTOMER" \
            --argjson pr_number "${PR_NUMBER:-0}" \
            --arg pr_branch "${PR_BRANCH:-}" \
            --arg image_tag "${IMAGE_TAG:-}" \
            --arg commit_sha "${COMMIT_SHA:-}" \
            --arg pr_title "${PR_TITLE:-}" \
            --arg pr_url "${PR_URL:-}" \
            --argjson config "${CONFIG:-{}}" \
            '{
              action: $action,
              partner: $partner,
              customer: $customer,
              pr_number: $pr_number,
              pr_branch: $pr_branch,
              image_tag: $image_tag,
              commit_sha: $commit_sha,
              pr_title: $pr_title,
              pr_url: $pr_url,
              config: $config
            }')")

        HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
        BODY=$(echo "$RESPONSE" | sed '$d')

        echo "Response: $HTTP_CODE"

        if [ "$HTTP_CODE" -ne 200 ]; then
          if [ "$ACTION" = "delete" ]; then
            echo "::warning::Preview may already be deleted"
            echo "success=true" >> $GITHUB_OUTPUT
            echo "message=Preview environment deleted or not found" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "::error::Failed to $ACTION preview"
            echo "$BODY" | jq . 2>/dev/null || echo "$BODY"
            echo "success=false" >> $GITHUB_OUTPUT
            exit 1
          fi
        fi

        # Parse response
        SUCCESS=$(echo "$BODY" | jq -r '.data.success // false')
        PREVIEW_URL=$(echo "$BODY" | jq -r '.data.previewUrl // empty')
        NAMESPACE=$(echo "$BODY" | jq -r '.data.namespace // empty')
        GIT_SHA=$(echo "$BODY" | jq -r '.data.gitCommitSha // empty')
        MESSAGE=$(echo "$BODY" | jq -r '.data.message // empty')

        echo "success=$SUCCESS" >> $GITHUB_OUTPUT
        echo "preview_url=$PREVIEW_URL" >> $GITHUB_OUTPUT
        echo "namespace=$NAMESPACE" >> $GITHUB_OUTPUT
        echo "git_commit_sha=$GIT_SHA" >> $GITHUB_OUTPUT
        echo "message=$MESSAGE" >> $GITHUB_OUTPUT

        if [ -n "$PREVIEW_URL" ]; then
          echo "Preview URL: $PREVIEW_URL"
        fi
        echo "$MESSAGE"

    - name: Comment on PR
      if: inputs.action != 'delete' && steps.preview.outputs.preview_url != ''
      uses: actions/github-script@v7
      with:
        script: |
          const previewUrl = '${{ steps.preview.outputs.preview_url }}';
          if (!previewUrl) return;

          const body = `## Preview Environment

          | | |
          |---|---|
          | **URL** | [${previewUrl}](${previewUrl}) |
          | **Branch** | \`${{ github.head_ref }}\` |
          | **Commit** | \`${{ github.event.pull_request.head.sha }}\` |

          > Preview available in ~2-3 minutes. Auto-deleted when PR closes.`;

          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const existing = comments.find(c => c.user.type === 'Bot' && c.body.includes('Preview Environment'));

          if (existing) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existing.id,
              body,
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });
          }
