name: 'Base Preview'
description: 'Manage PR preview environments on Norce Base Platform'
author: 'NorceTech'

branding:
  icon: 'eye'
  color: 'purple'

inputs:
  action:
    description: 'Action to perform (create, update, delete)'
    required: true
  image_tag:
    description: 'Image tag for the preview (not needed for delete)'
    required: false
  customer:
    description: 'Customer name (defaults to repository name)'
    required: false
  config_file:
    description: 'Path to config file'
    required: false
    default: '.base/config.yaml'
  api_url:
    description: 'Base Platform API URL'
    required: false
    default: 'https://base-api.norce.tech'
  api_key:
    description: 'Base Platform API key (identifies partner)'
    required: true

outputs:
  success:
    description: 'Whether the action was successful'
    value: ${{ steps.preview.outputs.success }}
  preview_url:
    description: 'URL of the preview environment'
    value: ${{ steps.preview.outputs.preview_url }}
  namespace:
    description: 'Kubernetes namespace'
    value: ${{ steps.preview.outputs.namespace }}
  git_commit_sha:
    description: 'Git commit SHA in GitOps repo'
    value: ${{ steps.preview.outputs.git_commit_sha }}
  message:
    description: 'Result message'
    value: ${{ steps.preview.outputs.message }}

runs:
  using: 'composite'
  steps:
    - name: Read configuration
      id: config
      if: inputs.action != 'delete'
      shell: bash
      env:
        CONFIG_FILE: ${{ inputs.config_file }}
      run: bash ${{ github.action_path }}/read-config.sh

    - name: Manage Preview Environment
      id: preview
      shell: bash
      env:
        API_URL: ${{ inputs.api_url }}
        API_KEY: ${{ inputs.api_key }}
        CUSTOMER: ${{ inputs.customer || github.event.repository.name }}
        ACTION: ${{ inputs.action }}
        IMAGE_TAG: ${{ inputs.image_tag }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        PR_BRANCH: ${{ github.head_ref }}
        COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_URL: ${{ github.event.pull_request.html_url }}
        CONFIG: ${{ steps.config.outputs.config }}
      run: bash ${{ github.action_path }}/preview.sh

    - name: Comment on PR
      if: inputs.action != 'delete' && steps.preview.outputs.preview_url != ''
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      env:
        PREVIEW_URL: ${{ steps.preview.outputs.preview_url }}
        HEAD_REF: ${{ github.head_ref }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      with:
        script: |
          const previewUrl = process.env.PREVIEW_URL;
          if (!previewUrl) return;

          const headRef = process.env.HEAD_REF;
          const headSha = process.env.HEAD_SHA;

          const body = `## Preview Environment

          | | |
          |---|---|
          | **URL** | [${previewUrl}](${previewUrl}) |
          | **Branch** | \`${headRef}\` |
          | **Commit** | \`${headSha}\` |

          > Preview available in ~2-3 minutes. Auto-deleted when PR closes.`;

          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const existing = comments.find(c => c.user.type === 'Bot' && c.body.includes('Preview Environment'));

          if (existing) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existing.id,
              body,
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });
          }
